import Header from "@/components/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Notflix",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#141414]`}>
        {!!session && <Header />}
        {children}
      </body>
    </html>
  );
}
